apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  # Your base64 encoded MongoDB credentials
  mongodb-uri: bW9uZ29kYitzcnY6Ly9zdWdhc2hzbXI6ZnRtVVk4a3FyMnE4a3RBckBjbHVzdGVyMC5zems4ay5tb25nb2RiLm5ldC90YXNrbWFuYWdlcj9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk= 