apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager
  template:
    metadata:
      labels:
        app: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: taskmanager:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://sugashsmr:ftmUY8kqr2q8ktAr@mongodb:27017/taskmanager?authSource=admin"
        - name: SPRING_DATA_MONGODB_DATABASE
          value: "taskmanager" 